###注册 中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 80
###网关名称
spring:
  application:
    name: service-zuul
### 配置网关反向代理
zuul:
  routes:
    api-producer:
      ### 以 /api-producer/访问转发到生产者服务
      path: /api-producer/**
      serviceId: SpringBoot-Producer
    api-consumer:
      ## 以 /api-order/访问转发到消费服务
      path: /api-consumer/**
      serviceId: SpringBoot-Consumer